services:
  web:
    build:
      context: .
      dockerfile: backend/Dockerfile
    ports:
      - "5000:5000"
    restart: unless-stopped
    volumes:
      # Monta el frontend para desarrollo (opcional - comentar en producción)
      - ./frontend:/frontend:ro

